# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
version: '3.7'

services:
  app:
    image: albatross:latest
    build:
      context: .
    environment:
        LOG_LEVEL: ${LOG_LEVEL:-debug}
        ADMIN_USERNAME: albatross
        ADMIN_PASSWORD: albatross
        ENABLE_TLS: false
    ports:
      - '8080:8080'
    volumes:
      - ./data:/app/data/
      - ./certs/cert.pem:/app/certs/cert.pem
      - ./certs/key.pem:/app/certs/key.pem
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command:
      [
        "serve",
        "--env",
        "production",
        "--hostname",
        "0.0.0.0",
        "--port",
        "8080"
      ]
