# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#      Start app: docker-compose up app
#       Stop all: docker-compose down
#
version: '3.7'

x-shared_environment:
  &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  ADMIN_USERNAME: albatross
  ADMIN_PASSWORD: albatross
  DB_URL: /app/data/db.sqlite
  TLS_CERT: /app/data/cert.pem
  TLS_KEY: /app/data/key.pem

services:
  app:
    image: albatross:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - migrate
    ports:
      - '8080:8080'
    volumes:
      - ./data:/app/data/
      - ./certs/cert.pem:/app/data/cert.pem
      - ./certs/key.pem:/app/data/key.pem
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command:
      [
        "serve",
        "--env",
        "production",
        "--hostname",
        "0.0.0.0",
        "--port",
        "8080"
      ]
  migrate:
    image: albatross:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    command: [ "migrate", "--yes" ]
    volumes:
      - ./data:/app/data/
    # deploy:
    #   replicas: 0
  revert:
    image: albatross:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    command: [ "migrate", "--revert", "--yes" ]
    volumes:
      - ./data:/app/data/
    deploy:
      replicas: 0
